library(sf)
library(dplyr)
library(readr)
library(raster)
library(bcmaps)
#library(rgdal)
library(fasterize)
library(readxl)
library(mapview)
library(WriteXLS)
library(foreign)
library(ggplot2)
library(ggnewscale)
library(viridis)
library(stars)
#library(rgrass7)
library(exactextractr)
library(expss)
library(openxlsx)
library(cleangeo)
library(geos)
library(tidyr)
library(plyr)
library(bcdata)
library(tmap)
library(smoothr)
library(terra)
library(rmapshaper)
library(tibble)
library(stringr)
library(fuzzyjoin)
library(purrr)
library(progress)

options(scipen=999)
options(warn = 1)
options(timeout=10000)

OutDir <- 'out'
dataOutDir <- file.path(OutDir,'data')
spatialOutDirP <- file.path(OutDir,'spatial')
DataDir <- 'data'
SpatialDir <- file.path(DataDir,'spatial')
#FieldData<-file.path(DataDir,'2023FieldData')
#OutDirWESP <-'../WESP_data_prep/out'
#dataOutDirWESP <- file.path(OutDirWESP,'data')
#spatialOutDirPWESP <- file.path(OutDirWESP,'spatial')
#DataDirWESP <- '../WESP_Sample_Design/data'
#GISLibrary<- file.path('/Users/darkbabine/ProjectLibrary/Library/GISFiles/BC')
#WESPDir <- file.path('../WESP_Sample_Design/data')
#BioDDir <- file.path('../../Biodiversity/data')
DrawDir <- file.path('../WESP_Sample_Draw/data')
WESPdata<-file.path('../../WESPdata')
dir.create(file.path(OutDir), showWarnings = FALSE)
dir.create(file.path(dataOutDir), showWarnings = FALSE)
dir.create(DataDir, showWarnings = FALSE)
dir.create(SpatialDir, showWarnings = FALSE)
dir.create("tmp", showWarnings = FALSE)
dir.create(file.path(spatialOutDirP), showWarnings = FALSE)

source('01_Load_Fns.R')


